### ISSUE TITLE
System seems to work not properly

### ISSUE THREAD

**Issue by romanbuehlervowa** [Octanis3/Octanis3-Data#2]
The system was already read out once and the data looked quite good.
Currently a female which is equipped with a NFC tag is breeding at the site so we expect to see some detections. On the second visit when psuhing the "flash memory to SD card" button the light stayed on exceptionally long (20 s). Viwing the data in the visualizer (https://www.cheminfo.org/?viewURL=https%3A%2F%2Fmydb.cheminfo.org%2Fdb%2Fvisualizer%2Fentry%2Febccc4defa108af950233a616146cf56%2Fview.json) results in a weird pattern on temperature and battery log and no real data points of detection. Data available under data section, file name: Verschezperrin.zip

**Comment by romanbuehlervowa** [comment]
So what do we do here? Try to exchange the system box? Its quite urgent as we have a breeding owl on this site.......

**Comment by traffael** [comment]
The system is ON during the entire logging period, as we can see in the battery voltage curve:

<img width="545" alt="Screenshot 2019-04-30 at 19 04 45" src="https://user-images.githubusercontent.com/2691289/56981982-78e88100-6b80-11e9-9f82-59616eba4188.png">

This means that the main controller is running without issues. But the weight data stops after just one day (it should continuously measure offset data even if there is no owl on the perch):

![Screenshot 2019-04-30 at 19 18 36](https://user-images.githubusercontent.com/2691289/56982065-b3eab480-6b80-11e9-8568-f52cb5d0e19d.png)

This indicated that the weight sensor chip may not be responding anymore due to an exception. It is possible that after a system restart, the problem gets resolved. If not, the chip itself may be damaged and the logger box should be replaced. The perch should be fine though!

**Comment by traffael** [comment]
An easy way to test if the chip still works: Turn on the Wifi, connect, enter calibration mode, and check if the values of the weight make senes and update over time (even with no additional weight on the perch).

**Comment by romanbuehlervowa** [comment]
We exchanged the system, but a restart obviously solved the problem here too. The data read out looked good....
