### ISSUE TITLE
Battery empty within less than one month

### ISSUE THREAD

**Issue by romanbuehlervowa** [Octanis3/Octanis3-Data#5]
The system in Birkenhof now twice showed the same problem that the batteries were empty within less than one month.

**Comment by traffael** [comment]
This system seems to be in "detection mode" all the time, i.e. the scale outputs a weight value that is above 80 grams, thinking there is a bird sitting on it. This is seen by the green dots in the visualizer (or the 'D' events in the log file)

<img width="566" alt="Screenshot 2019-04-27 at 02 35 52" src="https://user-images.githubusercontent.com/2691289/56842500-00d73e00-6896-11e9-8d2d-f7dd57a46583.png">

<img width="529" alt="Screenshot 2019-04-27 at 02 37 31" src="https://user-images.githubusercontent.com/2691289/56842501-00d73e00-6896-11e9-812f-497d034036b0.png">

Because of that, the RFID reader constantly tries to identify an owl. The RFID reader consumes the highest amount of current, which explains that the battery gets empty so quickly.

**Comment by traffael** [comment]
What is the ID of this Nestbox? Could you upload the file with calibration data & associated IDs?

**Comment by romanbuehlervowa** [comment]
Its Nr. ce50e34acc2c
File uploaded

So should we exchange the system box or the perch or even both?

**Comment by romanbuehlervowa** [comment]
During the control yesterday we saw that the system worked normally for the last 2 months, so the problem was solved by restarting it
